### ISSUE TITLE
load_model does not call Callbacks when setting the model

### ISSUE THREAD

**Issue by Jingnan-Jia** [IBM/tensorflow-large-model-support#21]
As @smatzek  mentioned in this issue:
https://github.com/keras-team/keras/issues/11279
load_model does not call Callbacks when setting the model.

I tried to load my model weights and retrain it using  a bigger input size, but it seems that tflms do not work any more and also a error or warning occurs:

`tensorflow/c/c_api.cc:326] Operation '{name:'loss_6/d1_loss/Mul' id:21252 op device:{} def:{{{node loss_6/d1_loss/Mul}} = Mul[T=DT_FLOAT](lms/swapin_loss_6_d1_loss_lambda_150_strided_slice_0:0, loss_6/d1_loss/lambda_151/strided_slice)}}' was changed by updating input tensor after it was run by a session. This mutation will have no effect, and will trigger an error in the future. Either don't modify nodes after running them or create a new session.`

So is this problem still not solved?

**Comment by smatzek** [comment]
I did open an API change request to Keras to introduce these changes. Getting it fixed in Keras would likely be required before proposing a similar change to TensorFlow Keras (tf.keras). The API change request never got properly reviewed.

In PowerAI and WMLCE we implemented the API changes in the Keras and TensorFlow Keras we provide in the WMLCE channel.

If you are using WMLCE I would suggest you carefully read the "Keras save and load considerations" section of the documentation. 
 https://www.ibm.com/support/knowledgecenter/SS5SF7_1.6.2/navigation/wmlce_getstarted_tflmsv2.html
The ordering of when the model is fully built, LMS is called, and weights loaded is important and depending which APIs you're calling the way you invoke LMS changes.

In terms of this repository's version of TFLMS this load_model issue is not fixed.

**Comment by smatzek** [comment]
A new implementation of TensorFlow Large Model Support has been released. This implementation does not require tuning and is easier to enable in your code. Please see the current master branch version of the README.md for more information. This new version of TensorFlow Large Model Support does not require changes to the Keras `load_model` API so I am closing this issue as resolved.
