### ISSUE TITLE
module 'tensorflow._api.v1.config.experimental' has no attribute 'set_lms_enabled'

### ISSUE THREAD

**Issue by nasica88** [IBM/tensorflow-large-model-support#27]
I am new to tensorflow LMS, and struggling with it from the start.

I tried to enable tensorflow LMS with "tf.config.experimental.set_lms_enabled(True)" as instructed in READEM on this github, but the it produces the following error.  

I am using tensorflow 1.15 from WML-CE 1.6.2 with python 3.7.5.

```
import tensorflow as tf
tf.version.VERSION

'1.15.0'
```

What did I do wrong ?
 

```
AttributeError                            Traceback (most recent call last)
<ipython-input-2-92d4b0125d7e> in <module>
     26 from tensorflow_large_model_support import LMS
     27 
---> 28 tf.config.experimental.set_lms_enabled(True)
     29 
     30 gpu_devices = ['/device:GPU:0', '/device:GPU:1', '/device:GPU:2', '/device:GPU:3']

~/anaconda3/envs/wmlce_env/lib/python3.7/site-packages/tensorflow_core/python/util/module_wrapper.py in __getattr__(self, name)
    191   def __getattr__(self, name):
    192     try:
--> 193       attr = getattr(self._tfmw_wrapped_module, name)
    194     except AttributeError:
    195       if not self._tfmw_public_apis:

AttributeError: module 'tensorflow._api.v1.config.experimental' has no attribute 'set_lms_enabled'
```

**Comment by smatzek** [comment]
Thank you for reaching out. The most current implementation of large model support is in TensorFlow 2.1.0 in WML CE's early access channel. For more information about the early access channel and how to use it you can see this [post](https://developer.ibm.com/linuxonpower/2020/02/10/using-the-watson-machine-learning-community-edition-auxiliary-channels/).

WML CE 1.6.2 does contain an implementation of large model support, named TFLMSv2. It's install and usage instructions are documented [here](https://www.ibm.com/support/knowledgecenter/SS5SF7_1.6.2/navigation/wmlce_getstarted_tflmsv2.html). However, since you are new to TensorFlow LMS I would suggest starting with the latest TensorFlow release (2.1.0) and the LMS implementation for it. The new LMS for TensorFlow 2 is much easier to use than the LMS for TensorFlow 1.x.

**Comment by bela127** [comment]
that you can find it for TensorFlow 2.1.0 in WML CE's early access channel could be mentioned in the readme of the LMS git repo.

**Comment by jayfurmanek** [comment]
TF 2.1 has since been promoted to the main WML CE channel and LMS is included, so the README is now accurate:
https://github.com/IBM/tensorflow-large-model-support#installing-tensorflow-large-model-support

**Comment by bela127** [comment]
Is it #29 ?
