### ISSUE TITLE
TF large model support compatibility requirements 

### ISSUE THREAD

**Issue by fouratthamri** [IBM/tensorflow-large-model-support#28]
I just want to know if the TF large model support feature is compatible with any CUDA enabled GPU card, or do I have to use it only on IBM Power Systems with V100's or P100's GPU cards as stated on the installation guideline page of the WML CE package. And is it compatible with Windows 64bit OS?

**Comment by smatzek** [comment]
WML CE has been built and tested for IBM Power System as x86 systems since 1.6.1. The GPUs supported have been V100s and P100s, and now in the latest release T4s are also added to the list. That is the supported GPU/platform list for WML CE.

TensorFlow Large Model Support does not have anything coded into it that would restrict it to that set of GPUs. IBM hasn't tested it on GPUs other than those but people have run it on other GPUs as evidenced by other issues on this repository. When you build CUDA programs you pass in the GPU architectures you are targeting to nvcc. For example, sm_70, compute_70, etc. If you try to run WML CE against GPUs other than the ones we support it may hit incompatibility issues with the nvcc GPU arch support. (See https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html)

The current version of TensorFlow Large Model Support is built into TensorFlow, so if you built TensorFlow from source with the LMS code applied to your source tree it should work on Windows.

The same applies for building TensorFlow for other nvcc sm/compute architectures with the LMS code applied to the tree.

**Comment by smatzek** [comment]
I would be interested to know if you are able to successfully build and run LMS on Windows or other NVIDIA/CUDA GPUs.
