### ISSUE TITLE
Use LMS with TF 2.1 Custom Training loops

### ISSUE THREAD

**Issue by alicebizeul** [IBM/tensorflow-large-model-support#52]
Hi all, 

I am training my network with TF 2.1 Custom Training Loops over batches and am trying to use LMS.
Is there a way to make this work ? 

Thank you !

**Comment by smatzek** [comment]
If you use tensorflow-gpu from the [WML CE conda channel](https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/#/) it should work. If you are using custom training loops I suspect you can just enable LMS with the line `tf.config.experimental.set_lms_enabled(True)` and not have to worry about the more specific steps mentioned on the readme.

Note that the main WML CE conda channel has TensorFlow 2.1. The ["early access channel"](https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda-early-access/) has LMS built into TensorFlow 2.2. No work has been done on LMS since TensorFlow 2.2 which has been about a year ago at this point.

**Comment by alicebizeul** [comment]
Thank you ! I already tried the option you mentioned by just setting` tf.config.experimental.set_lms_enabled(True)` at the beginning of my script. However the error messages I receive when moving to higher image resolutions still mention that `tensorflow/core/common_runtime/bfc_allocator.cc:809] Enabling Large Model Support may avoid this failure.` Is there a way to verify that TFLMS is enabled ? Thanks !

**Comment by smatzek** [comment]
If I remember correctly the TF 2.1 would output the `Enabling Large Model Support may avoid this failure.` message when the host allocator ran out of memory. I think I fixed this in TF 2.2 so the message will not show if the allocator is the host allocator.

See this section of the WML CE LMS documentation:
https://www.ibm.com/support/knowledgecenter/SS5SF7_1.7.0/navigation/wmlce_getstarted_tflms.html
"Increase the system memory (GPU host) memory allocation

TensorFlow sets a limit on the amount of memory that will be allocated on the GPU host (CPU) side. The limit is often not high enough to act as a tensor swap space when swapping a large amount of data or when using multiple GPUs without the use of Horovod. The limit can be adjusted by setting the TF_GPU_HOST_MEM_LIMIT_IN_MB environment variable. Failure to set this limit higher will result in out of memory errors such as:  Allocator (gpu_host_bfc) ran out of memory trying to allocate. Note the gpu_host_bfc allocator is mentioned rather than a GPU allocator.

The value for TF_GPU_HOST_MEM_LIMIT_IN_MB should be several times the size of the memory of the GPUs being used by the TensorFlow process. For example, if a single 32GB GPU is being used, the TF_GPU_HOST_MEM_LIMIT_IN_MB should be set several times greater than 32GB.

If Horovod distribution is being used, it will create one process per GPU. In this, the TF_GPU_HOST_MEM_LIMIT_IN_MB limit should be set several times greater than the memory of one of the GPUs.

If other GPU distribution mechanisms are used, the TF_GPU_HOST_MEM_LIMIT_IN_MB limit should be set to several times the sum of the memory of all the GPUs being used.
"

If you gather and share the messages you are seeing that are similar to the following, it will help understand if your process is running out of memory on the host or GPU side, and more details about the GPU memory allocation and LMS state when it failed:

`tensorflow/core/common_runtime/bfc_allocator.cc:685] Allocator (GPU_0_bfc) ran out of memory trying to allocate 7.92GiB (rounded to 8500515328)`

```
Limit:                         14675944448
InUse:                          8500841728
MaxInUse:                      13813929216
NumAllocs:                             120
MaxAllocSize:                   4249997312
BytesInactive:                           0
BytesActive:                    8500841728
PeakBytesActive:               12750059192
TotalBytesReclaimed:           37188580912
CurBytesReclaimed:             25501089536
NumSingleReclaims:                      11
NumFullReclaims:                         1
```

**Comment by alicebizeul** [comment]
Thank you very much for your message. I am training a GAN on high resolution images and am therefore using 16x32G GPUs with Horovod. I already set TF_GPU_HOST_MEM_LIMIT_IN_MB to 64000 and CPU RAM was increased to 800G in my bash script. Here are the error messages I am receiving:
![Capture d’écran 2021-03-31 à 16 05 12](https://user-images.githubusercontent.com/43455173/113171554-de9b8700-9247-11eb-9152-f10052e5454f.png)
![Capture d’écran 2021-03-31 à 16 05 36](https://user-images.githubusercontent.com/43455173/113171558-e0654a80-9247-11eb-9642-392462eb7ceb.png)

**Comment by smatzek** [comment]
Thanks. Your output shows that it IS the GPU allocator that is running out, you are not hitting the default 64GB limit on the system host memory. The output also shows that LMS has not done any swapping and is disabled (no bytes are shown as inactive, no reclaims, etc).

It looks like LMS isn't enabled on your model. Is your model using Estimators?

**Comment by alicebizeul** [comment]
No, I am using tf.Keras ! I will look for BytesReclaimed and BytesActive, in my next tests.

**Comment by smatzek** [comment]
Thanks. I suspect you are NOT using v1 compatibility mode since you have custom training loops, but if you have code like this:
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```
in your code you have to do more work with sessions to get LMS enabled.

As I said, I expect you are not doing this but I thought I would check.

Another thing you could check is to move the enablement of LMS earlier in your code. We did test with Horovod, and as you can see in the README we recommend it. You may need to ensure LMS is enabled before importing Horovod.

You may also want to simplify and try this without Horovod on a single GPU for some number of batches, just to see if you can get LMS swapping tensors for you before going distributed.

**Comment by alicebizeul** [comment]
I will try those options ! Will let you know. Thank you !

**Comment by alicebizeul** [comment]
I enabled LMS before Horovod and got the following error message. If I understand properly in this case it is the CPU which is running out of memory ? I will now try without Horovod on a single GPU. 
I also forgot to mention that the error message does not occur in the beginning of a image resolution increase but randomly in the middle of the training.

![Capture d’écran 2021-04-01 à 23 08 00](https://user-images.githubusercontent.com/43455173/113354740-e8a0b100-933f-11eb-969e-836c0b5fda49.png)
![Capture d’écran 2021-04-01 à 23 08 28](https://user-images.githubusercontent.com/43455173/113354745-ea6a7480-933f-11eb-9dbd-93054569f013.png)

**Comment by alicebizeul** [comment]
I enabled LMS before importing Horovod. I received this error message. If I understand correctly here the CPU is running out of memory ?  I will now try without Horovod and on a single GPU.

![Capture d’écran 2021-04-01 à 23 08 28](https://user-images.githubusercontent.com/43455173/113357750-c8272580-9344-11eb-8891-aaf3f20c9d2c.png)

![Capture d’écran 2021-04-01 à 23 08 00](https://user-images.githubusercontent.com/43455173/113357744-c6f5f880-9344-11eb-82de-0dfcf8f16541.png)

**Comment by smatzek** [comment]
You are right, the CPU memory space where inactive tensors are stored is running out of memory. This is actually good news in that LMS is working and doing the swapping.

You mention in a previous comment that you were setting `TF_GPU_HOST_MEM_LIMIT_IN_MB` to `64000`. That is the default value and it will limit the CPU side to 64GB, which is what we see in the logs above.

You should set that value higher. When I would run large models on 32GB GPUs I would set it to 256GB or higher.

One thing to note, which is also discussed in the README. When using Horovod, EACH GPU will get this amount of CPU/system memory allocated for it. With many GPUs you can easily run your system out of memory.

In my testing I also found that Horovod has GPU memory overhead which prevented me from achieving as high of resolution as was possible on a single GPU without Horovod.

**Comment by alicebizeul** [comment]
I think I understand better, thank you ! 

So to summarise if I request a job with 1T of CPU RAM, 16x32G GPUs then the maximum amount of `TF_GPU_HOST_MEM_LIMIT_IN_MB` that LMS can swap for each GPU is ~62.5G (16x62.5G=1T) which is not enough in my case. This requires that I reduce the number of GPUs I am using with LMS.

**Comment by smatzek** [comment]
Yes, that is correct if all 16 GPUs are on the same system.

I would suggest running with 1 GPU without Horovod. Tune the value of `TF_GPU_HOST_MEM_LIMIT_IN_MB` until training can get through many mini batches, and maybe a full epoch, depending on how much wall clock time you want to spend.

Once you have it running stable without getting out of memory errors at your chosen image resolution, you can use `top` to check the amount of memory the python process is using.  That will give you an idea of how many GPUs you could use without running the entire system out of memory or severely starving the operating system. I have done both while training a large 3D U-Net with 4x32 GPUs on a system with 1TB memory. The model I used is here: https://github.com/smatzek/3DUnetCNN

**Comment by alicebizeul** [comment]
Thank you for your help ! I am closing the issue as I now understand better how to handle memory ressources with TFLMS.
